---
 - hosts: all

   vars:
    - vpn_user: samflynn
    - vpn_pass: reallybigdoor
    - vpn_ip: 127.0.0.2
    - vpn_psk: secret

   roles: 
    - install-vpn-ppp-packages
    - configure-ppp
    - update-ip-tables
    - simple-vpn-connection
    - verify-vpn-connection
