---
 - hosts: all

   vars:
    - vpn_user: samflynn
    - vpn_pass: reallybigdoor
    - vpn_ip: 127.0.0.2
    - vpn_psk: secret

   roles: 
    - install-vpn-ppp-packages
    - configure-ppp
    - simple-vpn-connection
#    - configure-vpn-client
#    - update-ip-tables
    #- { role: trigger-vpn-service,  state: "started" }
    - verify-vpn-connection
#    - { role: trigger-vpn-service,  state: "stopped" }
