---
 - name: "does squid.default.conf exist?"
   shell: "file /etc/squid/squid.default.conf"
   register: squid_conf_exists
   ignore_errors: true

 - name: "backup squid.conf"
   shell: "cp /etc/squid/squid.conf /etc/squid/squid.default.conf"
   when: squid_conf_exists.rc != 0
   sudo: yes

 - name: "update squid configuration"
   copy: src=../files/squid.conf dest=/etc/squid/squid.conf
   sudo: yes

 - name: "restart squid"
   shell: "service squid restart"
   sudo: yes