---
 - name: "does named.conf.default.options exist?"
   shell: "file /etc/bind/named.conf.default.options"
   register: conf_exists
   ignore_errors: true

 - name: "backup named.conf.options"
   shell: "cp /etc/bind/named.conf.options /etc/bind/named.conf.default.options"
   when: conf_exists.rc != 0
   sudo: yes

 - name: "update bind configuration"
   copy: src=../files/named.conf.options dest=/etc/bind/named.conf.options
   sudo: yes

 - name: "restart bind"
   shell: "service bind9 restart"
   sudo: yes