---
 - name: "register ip"
   shell: "/sbin/ifconfig eth0 | grep 'inet addr' | awk -F: '{print $2}' | awk '{print $1}'"
   register: local_ip

 - name: "verify local ip"
   debug: var=local_ip
   when: debug | default(false)

 - name: "transfer xl2tpd.conf to /etc/xl2tpd/xl2tpd.conf"
   copy: src="../files/xl2tpd.conf" dest="/etc/xl2tpd/xl2tpd.conf"
   sudo: yes

 - name: "update xl2tpd.conf with vpn ip"
   command: "sed -i 's/_vpn_ip_/{{ vpn_ip }}/g' /etc/xl2tpd/xl2tpd.conf"
   sudo: yes

 - name: "transfer options.l2tpd.client to /etc/ppp/options.l2tpd.client"
   copy: src="../files/options.l2tpd.client" dest="/etc/ppp/options.l2tpd.client"
   sudo: yes

 - name: "update options.l2tpd.client with  vpn username"
   command: "sed -i 's/_vpn_user_/{{ vpn_user }}/g' /etc/ppp/options.l2tpd.client"
   sudo: yes

 - name: "update options.l2tpd.client with  vpn password"
   command: "sed -i 's/_vpn_password_/{{ vpn_pass }}/g' /etc/ppp/options.l2tpd.client"
   sudo: yes