---
 - name: "install pptpd"
   apt: name="pptpd" state="present" force="yes"
   sudo: yes

 - name: "backup /etc/ppp/chap-secrets"
   command: "cp /etc/ppp/chap-secrets /etc/ppp/chap-secrets.bk"
   sudo: yes

 - name: "transfer chap_secrets to /etc/ppp/chap-secrets"
   copy: src="../files/chap-secrets" dest="/etc/ppp/chap-secrets"
   sudo: yes

 - name: "update chap_secrets with username"
   command: "sed -i 's/_username_/{{ vpn_user }}/g' /etc/ppp/chap-secrets"
   sudo: yes

 - name: "update chap_secrets with password"
   command: "sed -i 's/_password_/{{ vpn_pass }}/g' /etc/ppp/chap-secrets"
   sudo: yes

 - name: "backup /etc/pptpd.conf"
   command: "cp /etc/pptpd.conf /etc/pptpd.conf.bk"
   sudo: yes

 - name: "transfer pptpd.conf to /etc/pptpd.conf"
   copy: src="../files/pptpd.conf" dest="/etc/pptpd.conf"
   sudo: yes

# backup before update

 - name: "backup /etc/ppp/options.pptpd"
   command: "cp /etc/ppp/options.pptpd /etc/ppp/options.pptpd.bk"
   sudo: yes


 - name: "transfer /etc/ppp/options"
   copy: src="../files/options.pptpd" dest="/etc/ppp/options.pptpd"
   sudo: yes