---
   # backup before update

 - name: "enable ipforwarding"
   command: "echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward"

 - name: "reload update iptables"
   command: "iptables -A FORWARD -o ppp0 -i eth0 -s 192.168.0.0/24 -m conntrack --ctstate NEW -j ACCEPT"
   sudo: yes

 - name: "reload update iptables"
   command: "iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT"
   sudo: yes

 - name: "reload update iptables"
   command: "iptables -t nat -F POSTROUTING"
   sudo: yes

 - name: "reload update iptables"
   command: "iptables -t nat -A POSTROUTING -o ppp0 -j MASQUERADE"
   sudo: yes
