---
 - name: "verify ip via strong vpn"
   shell: "curl -s strongvpn.com | grep images/flags | cut -d '\"' -f2"
   register: vpn_check

 - name: "validate vpn status"
   command: "echo validate vpn status"
   failed_when: "'us' not in vpn_check.stdout"