---
 - name: "register ip"
   shell: "/sbin/ifconfig eth0 | grep 'inet addr' | awk -F: '{print $2}' | awk '{print $1}'"
   register: local_ip

 - name: "verify local ip"
   debug: var=local_ip
   when: debug | default(false)

 - name: "transfer ipsec.conf to /etc/ipsec.conf"
   copy: src="../files/ipsec.conf" dest="/etc/ipsec.conf"
   sudo: yes

 - name: "update ipsec.conf with username"
   command: "sed -i 's/_localip_/{{ local_ip.stdout }}/g' /etc/ipsec.conf"
   sudo: yes

 - name: "update ipsec.conf with vpn ip"
   command: "sed -i 's/_vpn_ip_/{{ vpn_ip }}/g' /etc/ipsec.conf"
   sudo: yes

 - name: "transfer ipsec.secrets to /etc/ipsec.secrets"
   copy: src="../files/ipsec.secrets" dest="/etc/ipsec.secrets"
   sudo: yes

 - name: "update ipsec.secrets with local ip"
   command: "sed -i 's/_local_ip_/{{ local_ip.stdout }}/g' /etc/ipsec.secrets"
   sudo: yes

 - name: "update ipsec.secrets with vpn ip"
   command: "sed -i 's/_vpn_ip_/{{ vpn_ip }}/g' /etc/ipsec.secrets"
   sudo: yes

 - name: "update ipsec.secrets with vpn psk"
   command: "sed -i 's/_vpn_psk_/{{ vpn_psk }}/g' /etc/ipsec.secrets"
   sudo: yes

 - name: "transfer xl2tpd.conf to /etc/xl2tpd/xl2tpd.conf"
   copy: src="../files/xl2tpd.conf" dest="/etc/xl2tpd/xl2tpd.conf"
   sudo: yes

 - name: "update xl2tpd.conf with vpn ip"
   command: "sed -i 's/_vpn_ip_/{{ vpn_ip }}/g' /etc/xl2tpd/xl2tpd.conf"
   sudo: yes

 - name: "transfer options.l2tpd.client to /etc/ppp/options.l2tpd.client"
   copy: src="../files/options.l2tpd.client" dest="/etc/ppp/options.l2tpd.client"
   sudo: yes

 - name: "update options.l2tpd.client with  vpn username"
   command: "sed -i 's/_vpn_user_/{{ vpn_user }}/g' /etc/ppp/options.l2tpd.client"
   sudo: yes

 - name: "update options.l2tpd.client with  vpn password"
   command: "sed -i 's/_vpn_password_/{{ vpn_pass }}/g' /etc/ppp/options.l2tpd.client"
   sudo: yes

 - name: "create a route to vpn server"
   shell: "ip ro ad {{ vpn_ip }} via {{ local_ip.stdout }}"
   sudo: yes
   ignore_errors: true

 - name: "restart xl2tpd"
   shell: "invoke-rc.d xl2tpd restart"
   sudo: yes

 - name: "restart ipsec"
   shell: "invoke-rc.d ipsec restart"
   sudo: yes
   ignore_errors: true

 - name: "establish connection"
   shell: "ipsec auto --up L2TP-PSK"
   sudo: yes

 - name: "start ipsec"
   shell: "echo 'c vpn-conection' > /var/run/xl2tpd/l2tp-control"
   sudo: yes